// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.14.0
// source: service_spots.proto

package spots

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CloseSpotsServiceClient is the client API for CloseSpotsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CloseSpotsServiceClient interface {
	// ListSpotsNearPoint returns a list of spots around the location
	ListSpotsNearPoint(ctx context.Context, in *ListSpotsNearPointRequest, opts ...grpc.CallOption) (*ListSpotsNearPointResponse, error)
}

type closeSpotsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCloseSpotsServiceClient(cc grpc.ClientConnInterface) CloseSpotsServiceClient {
	return &closeSpotsServiceClient{cc}
}

func (c *closeSpotsServiceClient) ListSpotsNearPoint(ctx context.Context, in *ListSpotsNearPointRequest, opts ...grpc.CallOption) (*ListSpotsNearPointResponse, error) {
	out := new(ListSpotsNearPointResponse)
	err := c.cc.Invoke(ctx, "/spots.service.CloseSpotsService/ListSpotsNearPoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloseSpotsServiceServer is the server API for CloseSpotsService service.
// All implementations must embed UnimplementedCloseSpotsServiceServer
// for forward compatibility
type CloseSpotsServiceServer interface {
	// ListSpotsNearPoint returns a list of spots around the location
	ListSpotsNearPoint(context.Context, *ListSpotsNearPointRequest) (*ListSpotsNearPointResponse, error)
	mustEmbedUnimplementedCloseSpotsServiceServer()
}

// UnimplementedCloseSpotsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCloseSpotsServiceServer struct {
}

func (UnimplementedCloseSpotsServiceServer) ListSpotsNearPoint(context.Context, *ListSpotsNearPointRequest) (*ListSpotsNearPointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSpotsNearPoint not implemented")
}
func (UnimplementedCloseSpotsServiceServer) mustEmbedUnimplementedCloseSpotsServiceServer() {}

// UnsafeCloseSpotsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CloseSpotsServiceServer will
// result in compilation errors.
type UnsafeCloseSpotsServiceServer interface {
	mustEmbedUnimplementedCloseSpotsServiceServer()
}

func RegisterCloseSpotsServiceServer(s grpc.ServiceRegistrar, srv CloseSpotsServiceServer) {
	s.RegisterService(&CloseSpotsService_ServiceDesc, srv)
}

func _CloseSpotsService_ListSpotsNearPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSpotsNearPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloseSpotsServiceServer).ListSpotsNearPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spots.service.CloseSpotsService/ListSpotsNearPoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloseSpotsServiceServer).ListSpotsNearPoint(ctx, req.(*ListSpotsNearPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CloseSpotsService_ServiceDesc is the grpc.ServiceDesc for CloseSpotsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CloseSpotsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spots.service.CloseSpotsService",
	HandlerType: (*CloseSpotsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSpotsNearPoint",
			Handler:    _CloseSpotsService_ListSpotsNearPoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_spots.proto",
}
